[MIG] report_aeroo: Migration to 16.0
ingadhoc/aeroo_reports pull request #48
Opened 2022-11-10 16:48 UTC by matiasperalta1

2022-11-10 16:48 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/aeroo_reports/pull/48).

2022-12-01 18:17 UTC, nicomacr requested changes
@matiasperalta1 Grate work, only one thing to change.
Read the comment below

2022-12-01 18:17 UTC, nicomacr commented on report_aeroo/demo/.~lock.template.odt#
> +,mnp,mnp-nb.adhoc,29.11.2022 17:13,file:///home/mnp/.config/libreoffice/4;
This file must be erased.

2022-12-01 18:41 UTC, matiasperalta1 commented on report_aeroo/demo/.~lock.template.odt#
> +,mnp,mnp-nb.adhoc,29.11.2022 17:13,file:///home/mnp/.config/libreoffice/4;
@nicomacr Ready

2022-12-02 12:20 UTC, nicomacr commented
@roboadhoc r+

2022-12-02 12:37 UTC, roboadhoc commented
@matiasperalta1 @nicomacr because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

2022-12-02 12:45 UTC, nicomacr commented
@roboadhoc rebase-ff

2022-12-02 12:45 UTC, roboadhoc commented
Merge method set to rebase and fast-forward.

2022-12-02 17:30 UTC, merged